### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by martuitam** [eighty20results/e20r-mailchimp-for-membership-plugins#1]
Hi! I'm very new on this, so maybe I have done something wrong... ?

I have installed the plugin to give it a try, but I can't activate it. It says that license is not found. Not sure what it refers too or how to fix it. Would you please help?

Fatal error: Class 'E20R\Utilities\Licensing\License_Client' not found in /home/xxxxxxxxxxxxx/public_html/test/wp-content/plugins/e20r-mailchimp-for-membership-plugins-2.10/class/class.mailchimp-license.php on line 26

**Comment by eighty20results** [comment]
I'm so sorry I missed this bug report!

I'm guessing you've long since moved on, but if you haven't the licensing issue(s) from that version has long since been resolved. The current version should be all clear (v4.1.1)
